name: 'demo'

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  demo:
    name: 'demo'
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
    steps:
      - name: get credentials
        id: get-credentials
        uses: 'mozillazg/alibabacloud-oidc-auth@v1'
        with:
          role-arn-to-assume: '${{ secrets.ALIBABA_CLOUD_RAM_ROLE_ARN }}'
          oidc-provider-arn: '${{ secrets.ALIBABA_CLOUD_RAM_OIDC_ARN }}'
          set-outputs: 'true'

      - uses: aliyun/acr-login@v1
        with:
          region-id: ap-southeast-1
          access-key-id: ${{ steps.get-credentials.outputs.access-key-id }}
          access-key-secret: ${{ steps.get-credentials.outputs.access-key-secret }}
          security-token: ${{ steps.get-credentials.outputs.security-token }}
          
      - name: push image
        run: |
          docker pull alpine:3.16
          docker tag alpine:3.16 registry.ap-southeast-1.aliyuncs.com/${{ secrets.ACR_REPO }}
          docker push registry.ap-southeast-1.aliyuncs.com/${{ secrets.ACR_REPO }}

      # https://github.com/mozillazg/acr-scan/tree/support-sts-token-update-dist
      - uses: mozillazg/acr-scan@support-sts-token-update-dist
        with:
          region-id: ap-southeast-1
          access-key-id: ${{ steps.get-credentials.outputs.access-key-id }}
          access-key-secret: ${{ steps.get-credentials.outputs.access-key-secret }}
          security-token: ${{ steps.get-credentials.outputs.security-token }}
          repository: '${{ secrets.ACR_REPO }}'
          tag: 'latest'
